version: '3.4'

services:
  fibsrv:
    image: crookedstorm/fibsrv:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command:
      fibsrv
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./deployments/prometheus:/etc/prometheus/
      # - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    # image: budry/cadvisor-arm:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - fibsrv

# volumes:
#   prometheus-data: /prometheus

